In [1]:
import pandas as pd
import geopandas as gpd

#traffic volume csv
traffic=pd.read_csv('https://raw.githubusercontent.com/AlejandraZS10/capstone_project/master/data/Traffic_Volume_Counts__2014-2019_.csv')
traffic.head(10)

,ID,Segment ID,Roadway Name,From,To,Direction,Date,12:00-1:00 AM,1:00-2:00AM,2:00-3:00AM,...,2:00-3:00PM,3:00-4:00PM,4:00-5:00PM,5:00-6:00PM,6:00-7:00PM,7:00-8:00PM,8:00-9:00PM,9:00-10:00PM,10:00-11:00PM,11:00-12:00AM
0,2,70376,3 Avenue,East 154 Street,East 155 Street,NB,09/13/2014,204.0,177.0,133.0,...,520,611,573,546,582,528,432,328,282,240
1,2,70376,3 Avenue,East 155 Street,East 154 Street,SB,09/13/2014,140.0,51.0,128.0,...,379,376,329,362,418,335,282,247,237,191
2,56,176365,Bedford Park Boulevard,Grand Concourse,Valentine Avenue,EB,09/13/2014,94.0,73.0,65.0,...,280,272,264,236,213,190,199,183,147,103
3,56,176365,Bedford Park Boulevard,Grand Concourse,Valentine Avenue,WB,09/13/2014,88.0,82.0,75.0,...,237,276,223,240,217,198,186,162,157,103
4,62,147673,Broadway,West 242 Street,240 Street,SB,09/13/2014,255.0,209.0,149.0,...,732,809,707,675,641,556,546,465,425,324
5,62,158447,Broadway,West 242 Street,240 Street,NB,09/13/2014,255.0,209.0,149.0,...,732,809,707,675,641,556,546,465,425,324
6,62,255653,Broadway,West 242 Street,240 Street,SB,09/13/2014,87.0,86.0,78.0,...,200,200,209,175,181,167,144,129,112,103
7,71,139620,Bronx River Parkway,Bronx River,East Gun Hill Road,NB,09/13/2014,802.0,445.0,388.0,...,2933,2904,2699,2877,2947,2532,2193,1820,1677,1331
8,71,139618,Bronx River Parkway,East Gun Hill Road,Bronx River,SB,09/13/2014,618.0,345.0,309.0,...,2676,2848,2680,2581,2274,2054,1762,1534,1308,1107
9,76,70364,Brook Avenue,East 152 Street,East 153 Street,SB,09/13/2014,79.0,58.0,41.0,...,288,300,301,305,294,222,183,134,129,97

In [2]:
traffic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27289 entries, 0 to 27288
Data columns (total 31 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             27289 non-null  int64
 1   Segment ID     27289 non-null  int64
 2   Roadway Name   27289 non-null  object
 3   From           27289 non-null  object
 4   To             27289 non-null  object
 5   Direction      27289 non-null  object
 6   Date           27289 non-null  object
 7   12:00-1:00 AM  27285 non-null  float64
 8   1:00-2:00AM    27285 non-null  float64
 9   2:00-3:00AM    27285 non-null  float64
 10  3:00-4:00AM    27285 non-null  float64
 11  4:00-5:00AM    27285 non-null  float64
 12  5:00-6:00AM    27285 non-null  float64
 13  6:00-7:00AM    27285 non-null  float64
 14  7:00-8:00AM    27285 non-null  float64
 15  8:00-9:00AM    27285 non-null  float64
 16  9:00-10:00AM   27285 non-null  float64
 17  10:00-11:00AM  27286 non-null  float64
 18  11:00-12:00PM  27288 non-null  float64
 19  12:00-1:00PM   27289 non-null  int64
 20  1:00-2:00PM    27289 non-null  int64
 21  2:00-3:00PM    27289 non-null  int64
 22  3:00-4:00PM    27289 non-null  int64
 23  4:00-5:00PM    27289 non-null  int64
 24  5:00-6:00PM    27289 non-null  int64
 25  6:00-7:00PM    27289 non-null  int64
 26  7:00-8:00PM    27289 non-null  int64
 27  8:00-9:00PM    27289 non-null  int64
 28  9:00-10:00PM   27289 non-null  int64
 29  10:00-11:00PM  27289 non-null  int64
 30  11:00-12:00AM  27289 non-null  int64
dtypes: float64(12), int64(14), object(5)
memory usage: 6.5+ MB

In [ ]:
traffic['Roadway Name'] = traffic['Roadway Name'].str.lower()
traffic['From'] = traffic['From'].str.lower()
traffic['To'] = traffic['To'].str.lower()
traffic.head(5)

In [ ]:
traffic['Roadway Name'] = traffic['Roadway Name'].str.replace('east ', 'e ') 
traffic['From'] = traffic['From'].str.replace('east ', 'e ') 
traffic['To'] = traffic['To'].str.replace('east ', 'e ') 
traffic['Roadway Name'] = traffic['Roadway Name'].str.replace('west ', 'w ') 
traffic['From'] = traffic['From'].str.replace('west ', 'w ') 
traffic['To'] = traffic['To'].str.replace('west ', 'w ')